### ISSUE TITLE
extension settings show that 3.12.0 is available while running 3.15.0

### ISSUE THREAD

**Issue by averyfreeman** [arononak/github-actions-gnome-extension#5]
Not sure if you're actively maintaining this, it's a neat idea for an extension.

Expected: 

Extension update to alert me about a newer version than I am using.

Actual:

Extension update alerts me of an older version than I am using.

![image](https://github.com/arononak/github-actions-gnome-extension/assets/1308847/e2ed0d9c-bf4d-4ca9-9f58-2a8bcffda986)

**Comment by arononak** [comment]
@averyfreeman Of course i maintains it! It releases a new version every Friday. Thanks for the message. Write whether you want to be on the honorary list in the extension and give a star to the project 🙂

**Comment by arononak** [comment]
@averyfreeman 
I checked this module and it looks like it can't download the latest version from github. Could you please write whether the problem was resolved after the update ?

if not:
1. whether you are logged in to GitHub CLI ?
2. whether you have access to the Internet from the extension (does the extension download data)\
3. the system language `echo $LANG`

**Comment by arononak** [comment]
Closed
